application: codeigniter-gae-app
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /user_guide
  static_dir: user_guide

- url: /
  script: index.php

- url: /(.+)
  script: index.php